### ISSUE TITLE
Weird spacing of the logo and title

### ISSUE THREAD

**Issue by jocelynpender** [gbif/hp-canadian-biodiversity#5] opened 2021-03-04 14:20 UTC
**Describe the bug**
The title "CBIF" overlaps with the "About" button in the header. This bug doesn't seem to exist on the demo site @MortenHofft showed us last time.

**Expected behavior**
The title does not overlap with the "About" button in the header

**Screenshots**
![image](https://user-images.githubusercontent.com/16246446/109977222-9cc00500-7cca-11eb-9509-8260bbb427f0.png)

**Desktop (please complete the following information):**
 - MacOS High Sierra 10.13.6
 - Chrome Version 88.0.4324.182 (Official Build) (x86_64)

TODO: Test with different browsers and devices.

**Comment by MortenHofft** [comment] 2021-03-05 15:14
Closing as duplicate of https://github.com/gbif/hosted-portals/issues/38

Hi @jocelynpender 
It turns out the issue could be solved by adding a size to the SVG. I've done so in your repo

you can see a more detailed explanation on the other issue

**Closed as completed by MortenHofft** 2021-03-05 15:14 UTC
Labels: bug
